# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: gpt-chatbot

tasks:
  default:
    cmds:
      - task -a --sort none

  local-build:
    dir: ./local
    cmd: docker compose -p {{.PROJECT_NAME}} build

  local-up:
    dir: ./local
    cmd: docker compose -p {{.PROJECT_NAME}} up -d

  local-build-up:
    cmds:
      - task: local-build
      - task: local-up
